### PR TITLE
Chore: update master for T3 test release build

### PR DESCRIPTION
**Pull request by simonf7**

### CODE REVIEW

**Review by alexwyett — APPROVED** [review]

**Comment by alexwyett** [comment]
I haven't seen getCommentsAndMetrics benig used but thought maybe its used in the portal? Have you used it before @cdobson?

**Comment by simonf7** [comment]
> I haven't seen getCommentsAndMetrics benig used but thought maybe its used in the portal? Have you used it before @cdobson?

It's used in the new property reviews block, just building a test server for Dan to test with - decided to keep out of develop for now as I imagine there'll be a load of changes and don't want to hold up normal releases.

**Comment by alexwyett** [comment]
> > I haven't seen getCommentsAndMetrics benig used but thought maybe its used in the portal? Have you used it before @cdobson?
> 
> It's used in the new property reviews block, just building a test server for Dan to test with - decided to keep out of develop for now as I imagine there'll be a load of changes and don't want to hold up normal releases.

Yeah thats fine - just wondered if any other app might be using the method with the old parameters.

**Comment by cdobson** [comment]
> Yeah thats fine - just wondered if any other app might be using the method with the old parameters.

Nah

**Review by cdobson — APPROVED** [review]

**Pull request merged**
